module Fedex
  VERSION = "3.10.4.2"
  API_VERSION = "13"
  SHIP_API_VERSION = "23"
  RATE_API_VERSION = "24"
  ADDRESS_API_VERSION = "4"
  PICKUP_API_VERSION = "9"
  SERVICE_AVAILABILITY_API_VERSION = "5"
end
